import React from 'react';
import Button from './ui/Button';
import Card from './ui/Card';
import ProgressTracker from './ProgressTracker';
import { DumbbellIcon, FlameIcon, HeartPulseIcon } from './icons/Icons';

interface HeroSectionProps {
  onCtaClick: () => void;
}

const HeroSection: React.FC<HeroSectionProps> = ({ onCtaClick }) => {
  return (
    <div className="space-y-24 md:space-y-48 pb-24">
      {/* Hero */}
      <section className="relative h-[80vh] md:h-screen flex items-center justify-center text-center overflow-hidden">
        <div className="absolute inset-0 bg-cover bg-center bg-no-repeat z-0" style={{ backgroundImage: `url(https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=2575&auto=format&fit=crop)` }}>
            <div className="absolute inset-0 bg-black/80"></div>
        </div>
        <div className="relative z-10 container mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-5xl md:text-7xl lg:text-8xl font-heading font-extrabold text-white uppercase tracking-wider animate-fade-in-down">
            Transform Your Body
            <br />
            <span className="text-red-500">Master Your Mind</span>
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg md:text-xl text-gray-300 animate-fade-in-up">
            The ultimate all-in-one fitness hub. Track, plan, and conquer your goals with elite tools and AI-powered guidance.
          </p>
          <div className="mt-10">
            <Button onClick={onCtaClick} size="lg" className="animate-pulse-glow">
              Start My Transformation
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-4xl md:text-5xl font-heading text-center font-bold">An Entire Gym in Your Pocket</h2>
        <p className="text-center mt-4 text-gray-400 max-w-2xl mx-auto">Everything you need to succeed, centralized in one powerful platform.</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
            <Card className="text-center p-8">
                <DumbbellIcon className="mx-auto h-12 w-12 text-red-500" />
                <h3 className="font-heading text-2xl mt-4">Workout Planning</h3>
                <p className="text-gray-400 mt-2">Get a personalized plan generated by AI, tailored to your goals and schedule.</p>
            </Card>
            <Card className="text-center p-8">
                <HeartPulseIcon className="mx-auto h-12 w-12 text-red-500" />
                <h3 className="font-heading text-2xl mt-4">Nutrition Tracking</h3>
                <p className="text-gray-400 mt-2">Log meals, track macros, and monitor hydration to fuel your progress.</p>
            </Card>
            <Card className="text-center p-8">
                <FlameIcon className="mx-auto h-12 w-12 text-red-500" />
                <h3 className="font-heading text-2xl mt-4">Progress Visualized</h3>
                <p className="text-gray-400 mt-2">See your journey with powerful graphs, stats, and photo timelines.</p>
            </Card>
        </div>
      </section>

      {/* Progress Tracker Preview */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-4xl md:text-5xl font-heading text-center font-bold">Visualize Your Victory</h2>
         <p className="text-center mt-4 text-gray-400 max-w-2xl mx-auto">Our dashboard gives you a crystal-clear view of your hard work paying off.</p>
        <div className="mt-12">
            <ProgressTracker isPreview={true}/>
        </div>
      </section>

    </div>
  );
};

export default HeroSection;
